### ISSUE TITLE
Operator is not able to handle custom machineconfigpool properly

### ISSUE THREAD

**Issue by bpradipt** [openshift/sandboxed-containers-operator#107]
**Description**

When using custom machineconfig pool like the one shown below, different problems are encountered. For example adding a new node to the MCP doesn't trigger reconcile.  Deleting the CR doesn't work.
```
apiVersion: kataconfiguration.openshift.io/v1
kind: KataConfig
metadata:
 name: example-kataconfig
spec:
 kataConfigPoolSelector:
 matchLabels:
 custom-kata1: test
```

**Steps to reproduce the issue:**

Case-1
$ oc label node worker0.ocp4.example.com custom-kata1=test
$ oc create -f custom_kataconfig.yaml
Once install succeeds, label the other worker
$ oc label node worker1.ocp4.example.com custom-kata1=test

**Describe the results you received:**
Watch the Kataconfig CR. The status will not get updated

**Describe the results you expected:**
Kataconfig CR should show updated status with new node info

Case-2
$ oc label node worker0.ocp4.example.com custom-kata1=test
$ oc label node worker1.ocp4.example.com custom-kata1=test
$ oc create -f custom_kataconfig.yaml
Once installation is over, delete the KataConfig CR.  

**Describe the results you received:**
Delete never completes.

**Describe the results you expected:**
Successful deletion
