### ISSUE TITLE
NodeSelector is not being set for RuntimeClass when using MatchExpressions in KataConfigPoolSelector

### ISSUE THREAD

**Issue by bpradipt** [openshift/sandboxed-containers-operator#118]
**Description**
NodeSelector is not being set for RuntimeClass when using MatchExpressions in KataConfigPoolSelector

**Steps to reproduce the issue:**
1. Create KataConfig from OpenShift UI which uses `matchExpressions` or use the following yaml
```
apiVersion: kataconfiguration.openshift.io/v1
kind: KataConfig
metadata:
  name: example-kataconfig
spec:
  kataConfigPoolSelector:
     matchExpressions:
       - key: custom-kata1
         operator: In
         values:
         - "test"
```

**Describe the results you received:**

Kata runtime will be successfully installed on the nodes labelled with `custom-kata1=test`, however NodeSelector settings in RuntimeClass will be empty
`oc get runtimeclass kata -o yaml`

```
scheduling:
  nodeSelector: {}
```

**Describe the results you expected:**
`oc get runtimeclass kata -o yaml`

```
scheduling:
    nodeSelector:
        custom-kata1: test
```
