### ISSUE TITLE
Enhance the usability of the Libvirt provider for confidential container administrators

### ISSUE THREAD

**Issue by savitrilh** [openshift/sandboxed-containers-operator#435]
## Summary

To improve the user experience for confidential container administrators to enable the confidential container functionality, sandbox container operators should utilize a specialized script designed for Libvirt provider for managing administrative tasks specific to confidential containers during the activation of Peerpod through the KataConfig configmap.

## Motivation

Currently, the OpenShift Sandbox Container(OSC) Operator manages the following tasks:

- This manages the lifecycle (install/configure/update) of sandboxed containers runtime (Kata containers) on OpenShift clusters.
- Build the PODVM QCOW2 image or pull the PODVM image from the registry, extract the PODVM image from a container wrapped QCOW2 image.
-  Uploads the operator built or pulled pre-built PODVM image to pre-created Libvirt volume. 

OSC operator handles above operations automatically but still it requires following manual operations to be executed by confidential container administrator:

**1. Generation of SSH Key(public-private key) in OCP cluster.**

`$ ssh-keygen -f ./id_rsa -N ""`

 **2. Copy the SSH public key to KVM Host(LPAR). So that worker node can perform Libvirt specific operations such as creating the peerpod on the LPAR(KVM host) and lifecycle management of the peerpod VM.**

`$ ssh-copy-id -i ./id_rsa.pub <KVM_HOST_IP_ADDRESS>`

 **3. Create the SSH secret object**

```
$ oc create secret generic ssh-key-secret \
    -n openshift-sandboxed-containers-operator \
    --from-file=id_rsa.pub=./id_rsa.pub \
    --from-file=id_rsa=./id_rsa
```

**4. Create Libvirt POOL and Volume**

**Set the name of the libvirt pool by running the following command:** 	      
`$ export LIBVIRT_POOL=<name_of_libvirt_pool_to_create>`

**Set the name of the libvirt volume by running the following command:**     
` $ export LIBVIRT_VOL_NAME=<name_of_libvirt_volume_to_create>`

**Set the path of the default storage pool location, by running the following command:**								
`$ export LIBVIRT_POOL_DIRECTORY=<name_of_target_directory> `
 
_Note:To ensure libvirt has read and write access permissions, use a subdirectory of libvirt’s storage directory. The default is /var/lib/libvirt/images/_		
							
**Create a libvirt pool by running the following command:** 				
`$ virsh pool-define-as $LIBVIRT_POOL --type dir --target "$LIBVIRT_POOL_DIRECTORY"`

**Start the libvirt pool by running the following command:** 				
$ virsh pool-start $LIBVIRT_POOL

**5. Create and apply the PeerPod Secret and ConfigMap.**

**1. Create and apply the PeerPod Secret**

**Create a YAML file peer-pods-secret.yaml with the following manifest:** 	
	
```
apiVersion: v1
kind: Secret
metadata:
  name: peer-pods-secret
  namespace: openshift-sandboxed-containers-operator
type: Opaque
stringData:
  CLOUD_PROVIDER: "libvirt" [1](https://docs.redhat.com/en/documentation/openshift_sandboxed_containers/1.5/html-single/openshift_sandboxed_containers_user_guide/index#CO17-1)
  LIBVIRT_URI: "<libvirt_gateway_uri>" [2](https://docs.redhat.com/en/documentation/openshift_sandboxed_containers/1.5/html-single/openshift_sandboxed_containers_user_guide/index#CO17-2)
  LIBVIRT_POOL: "<libvirt_pool>" 3
  LIBVIRT_VOL_NAME: "<libvirt_volume>" 4

```
1 Enter libvirt as the cloud provider. 									
2 Enter the libvirt_gateway_uri value you retrieved. 									
3 (https://docs.redhat.com/en/documentation/openshift_sandboxed_containers/1.5/html-single/openshift_sandboxed_containers_user_guide/index#CO17-3) Enter the libvirt_pool value you retrieved. 									
4 (https://docs.redhat.com/en/documentation/openshift_sandboxed_containers/1.5/html-single/openshift_sandboxed_containers_user_guide/index#CO17-4) Enter the libvirt_volume value you retrieved. 

**2. Create the peer-pod-secret object:** 								
						
`$ oc apply -f peer-pods-secret.yaml`
	
**3. Create and apply ConfigMap.**

Create a peerpod configuration file(peer-pods-cm.yaml)

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: peer-pods-cm
  namespace: openshift-sandboxed-containers-operator
data:
  CLOUD_PROVIDER: "libvirt"
  PROXY_TIMEOUT: "15m"
```
**Apply the ConfigMap:** 

$ oc apply -f peer-pods-cm.yaml

**4. Create Libvirt image config map** 
**i. For Operator built PodVM image**
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: libvirt-podvm-image-cm
  namespace: openshift-sandboxed-containers-operator
data:
  # PodVM image distro
  PODVM_DISTRO: "rhel"

  # Pod VM sources
  # If changing the source, then ensure the respective payload binaries are available
  # for the new source
  CAA_SRC: "https://github.com/confidential-containers/cloud-api-adaptor"
  CAA_REF: "v0.8.2"

  # Booleans
  DOWNLOAD_SOURCES: "no"
  CONFIDENTIAL_COMPUTE_ENABLED: "no"
  UPDATE_PEERPODS_CM: "yes"

  # Libvirt specific
  ORG_ID: ""
  ACTIVATION_KEY: ""
  BASE_OS_VERSION: "9.4"

  # To Enable SE for IBM Z
  SE_BOOT: "true"
```

**ii. For Pre built PodVM image**
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: libvirt-podvm-image-cm
  namespace: openshift-sandboxed-containers-operator
data:
  # PodVM image distro
  PODVM_DISTRO: "rhel"

  # Pod VM sources
  # If changing the source, then ensure the respective payload binaries are available
  # for the new source
  CAA_SRC: "https://github.com/confidential-containers/cloud-api-adaptor"
  CAA_REF: "v0.8.2"

  # Booleans
  DOWNLOAD_SOURCES: "no"
  CONFIDENTIAL_COMPUTE_ENABLED: "no"
  UPDATE_PEERPODS_CM: "yes"

  # Libvirt specific
  ORG_ID: ""
  ACTIVATION_KEY: ""
  BASE_OS_VERSION: "9.4

  # For Pre-built PodVM images.
  PODVM_IMAGE_URI: "" # eg: oci::quay.io/openshift_sandboxed_containers/libvirt-podvm-image:latest::/image/podvm.qcow2
```
		
The goal is to enhance user experience by automating the aforementioned manual operations through a script. These scripts will be called from OSC through job.

## Goals

To improve the user experience for confidential container administrators to enable the confidential container functionality, sandbox container operators should utilize a specialized script designed for Libvirt provider for managing administrative tasks specific to confidential containers during the activation or de-activation of Peerpod through the KataConfig configmap. 

## Proposal

This new script `libvirt-config-manager.sh` will be developed and shipped with openshift sandbox container operator. This script can be called for s390x Libvirt provider in the reconcile path(routine) of the openshift sandbox container in the functions `processKataConfigInstallRequest` and `handleFeatureConfidential`. This reduces the manual operation.

## Design

This design focuses to improve the usability experience for the OCP Admin user to enable the confidential containers.

Four new files `libvirt-podvm-secret.yaml`,  `libvirt-config-manager.sh`, `osc-podvm-pre-config-job.yaml`  and `osc-cleanup.yaml` will be added to improve the usability.

`libvirt-podvm-secret.yaml` file will contain the following fields(Keys)
1. KVM HOST(LPAR) IP -> where OCP worker nodes are running
2. KVM HOST Username
3. KVM HOST password (Encode the password)
4. Directory path (Location of the Libvirt Pool)  
6. Libvirt Pool Name 
7. Libvirt Volume name
8. SE_BOOT: "true
9. PODVM_IMAGE_URI
......
KVM HOST(LPAR) IP, KVM HOST Username and KVM HOST password are mandatory fields. Libvirt Pool Path, Pool Name Volume names,  SE_BOOT and PODVM_IMAGE_URI are optional.

Note: Administrators need to create a user on the LPAR with the necessary permissions to execute virsh commands and apply the Libvirt configuration file`libvirt-podvm-secret.yaml` on the OpenShift Container Platform (OCP) before enabling peerpods through KataConfig configmap.

The `libvirt-config-manager.sh` script utilizes the administrative user's specified data from the `libvirt-podvm-secret.yaml` file.

The `libvirt-config-manager.sh` script sequentially executes the following tasks.
1. Validate the mandatory field values in the `libvirt-podvm-secret.yaml` file.
2. Generate a SSH key pair (public-private key) within the OCP cluster.
3. Decode the encoded KVM host password as specified in `libvirt-podvm-secret.yaml`.
4. Copy the generated SSH public key to the KVM Host(LPAR).
5. Create the SSH secret object on OCP 
6. Create the directory on the KVM host where the user specifies the path for the default storage pool location.
8. Create a Libvirt pool using the specified pool name if specified by the admin user in the `libvirt-podvm-secret.yaml` file. Otherwise, create the libvirt pool using the default pool name.
9. Start the created libvirt pool 
11. Create a Libvirt volume using the specified volume name if specified by the admin user in the `libvirt-podvm-secret.yaml` file. Otherwise, create the libvirt volume using the default volume name.

12. Generate and apply PeerPod Secret, PeerPod ConfigMap and Libvirt Image ConfigMap.

This script `libvirt-config-manager.sh` will be shipped with openshift sandbox container operator. This script can be called for s390x Libvirt provider in reconcile path(routine) of the openshift sandbox container in the functions `processKataConfigInstallRequest` and `handleFeatureConfidential` through the jobs `osc-podvm-pre-config-job.yaml`  and `osc-cleanup.yaml` to create Secrets, ConfigMaps, Libvirt Pool and Volume during PeerPod activation and remove them during PeerPod de-activation through jobs.

## Future Work Items related to this

Currently, the KVM host (LPAR) password is encoded and applied via script for the Tech Preview phase. For the General Availability (GA) release, TLS server certificates will be generated and stored securely, similar to other credentials. The plan is to establish a TLS connection between the LPAR and OCP host, enabling secure transmission of the SSH public key generated on OCP to the LPAR.

## Conclusion

This approach improves user experience for confidential container administrators to enable/disable the confidential container functionality, sandbox container operators should utilize a specialized
script designed for Libvirt provider for managing administrative tasks specific to confidential containers during the activation or de-activation of Peerpod through the KataConfig configmap.

**This proposal can be found in following google document:**
https://docs.google.com/document/d/1ZfgG2PJXs4FeKeV5RkGGkrJ_MLZJxX5smSGrOiN8ZUw/edit
